# scara config
arm: 
  communincation_frequency: 50 #Hz

  odrive_serial_number:
    odrive0: "206834615748"
    odrive1: "207C349F5748"

  joint1:
    name: arm/joint1
    odrive:
      id: 0
      axis: 1
    limit:
      position:
        max: 2.879793266
        min: -2.879793266
      velocity: 20.0
      current: 20.0
    tolerence: 0.3
    offset: -2.421191657

  joint2:
    name: arm/joint2
    odrive:
      id: 0
      axis: 0
    limit:
      position:
        max: 2.705260341
        min: -2.705260341
      velocity: 10.0
      current: 24.0
    tolerence: 0.3
    offset: 2.570511031

  joint3:
    name: arm/joint3
    odrive:
      id: 1
      axis: 1
    limit:
      position:
        max: 3.054326191
        min: -3.054326191
      velocity: 10.0
      current: 12.0
    tolerence: 0.3
    offset: -0.601013654

  joint4:
    name: arm/joint4
    odrive:
      id: 1
      axis: 0
    limit:
      position:
        max: 0.01
        min: -0.26
      velocity: 10.0
      current: 24.0
    tolerence: 0.05
    offset: -0.006396468639
