arm: 
  communincation_frequency: 50 #Hz

  odrive_serial_number:
    odrive0: "207C34805748"
    odrive1: "206834615748"
    odrive2: "207C349F5748"

  joint1:
    name: arm/joint1
    odrive:
      id: 0
      axis: 0
    limit:
      position:
        max: 2.0
        min: -2.0
      velocity: 10.0
      current: 10.0
    tolerence: 0.5
    offset: 0.7533075219
    reduction ratio: 8
    kp: 50.0
    kd: 0.5
    default:
      velocity: 2.0
      acceleration: 3.0

  joint2:
    name: arm/joint2
    odrive:
      id: 1
      axis: 0
    limit:
      position:
        max: 2.0
        min: -2.0
      velocity: 10.0
      current: 10.0
    tolerence: 0.5
    offset: -0.8341267922948693014
    reduction ratio: 16
    kp: 50.0
    kd: 0.5
    default:
      velocity: 2.0
      acceleration: 3.0

  joint3:
    name: arm/joint3
    odrive:
      id: 1
      axis: 1
    limit:
      position:
        max: 10.0
        min: -10.0
      velocity: 10.0
      current: 10.0
    tolerence: 0.5
    offset: 2.25086768698
    reduction ratio: 8
    kp: 50.0
    kd: 0.5
    default:
      velocity: 2.0
      acceleration: 3.0

  joint4:
    name: arm/joint4
    odrive:
      id: 2
      axis: 0
    limit:
      position:
        max: 10.0
        min: -10.0
      velocity: 10.0
      current: 10.0
    tolerence: 0.5
    offset: 0.0
    reduction ratio: 2.8
    kp: 50.0
    kd: 0.5
    default:
      velocity: 2.0
      acceleration: 3.0

  joint5:
    name: arm/joint5
    odrive:
      id: 2
      axis: 1
    limit:
      position:
        max: 10.0
        min: -10.0
      velocity: 10.0
      current: 10.0
    tolerence: 0.5
    offset: 0.0
    reduction ratio: 2.8
    kp: 50.0
    kd: 0.5
    default:
      velocity: 2.0
      acceleration: 3.0