joint1:
  id: 1
  name: arm/joint1
  position:
    limit:
      max: 1.6
      min: -1.6
    tolerence: 0.2
    offset: 0.0
  velocity:
    limit: 10.0
    default: 5.0
  acceleration: 
    default: 5.0
  current: 
    limit: 10.0
  kp: 50.0
  kd: 0.2