# scara config
arm: 
  communincation_frequency: 50 #Hz

  odrive_serial_number:
    odrive0: "206834615748"
    odrive1: "207C349F5748"

  joint1:
    name: arm/joint1
    odrive:
      id: 0
      axis: 1
    limit:
      position:
        max: 2.82743
        min: -2.82743
      velocity: 20.0
      current: 24.0
    tolerence: 0.3
    offset: -2.613519086

  joint2:
    name: arm/joint2
    odrive:
      id: 0
      axis: 0
    limit:
      position:
        max: 2.82743
        min: -2.82743
      velocity: 10.0
      current: 24.0
    tolerence: 0.3
    offset: 2.629361016

  joint3:
    name: arm/joint3
    odrive:
      id: 1
      axis: 1
    limit:
      position:
        max: 2.82743
        min: -2.82743
      velocity: 10.0
      current: 24.0
    tolerence: 0.3
    offset: -0.7517228573

  joint4:
    name: arm/joint4
    odrive:
      id: 1
      axis: 0
    limit:
      position:
        max: 0.1
        min: -0.25
      velocity: 10.0
      current: 24.0
    tolerence: 0.3
    offset: -0.001945500016
