# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm0
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm/joint1
    - arm/joint2
    - arm/joint3
    - arm/joint4
    - arm/joint5
    - gripper/joint1
    - gripper/joint2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_joint1_controller:
  type: position_controllers/JointPositionController
  joint: arm/joint1
arm_joint2_controller:
  type: position_controllers/JointPositionController
  joint: arm/joint2
arm_joint3_controller:
  type: position_controllers/JointPositionController
  joint: arm/joint3
arm_joint4_controller:
  type: position_controllers/JointPositionController
  joint: arm/joint4
arm_joint5_controller:
  type: position_controllers/JointPositionController
  joint: arm/joint5

controller_list:
  - name: hand2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      gripper/joint2
  - name: hand1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      gripper/joint1